set_property PACKAGE_PIN A10 [get_ports perst_n]
set_property IOSTANDARD LVCMOS33 [get_ports perst_n]
set_property PULLDOWN true [get_ports perst_n]
set_false_path -from [get_ports perst_n]

set_property PACKAGE_PIN A9 [get_ports clkreq_n]
set_property IOSTANDARD LVCMOS33 [get_ports clkreq_n]
set_property PULLDOWN true [get_ports clkreq_n]

set_property PACKAGE_PIN B6 [get_ports refclk_p]
create_clock -period 10.000 -name sys_clk [get_ports refclk_p]

set_property PACKAGE_PIN G4 [get_ports per0_p]
set_property PACKAGE_PIN G3 [get_ports per0_n]
set_property PACKAGE_PIN B2 [get_ports pet0_p]
set_property PACKAGE_PIN B1 [get_ports pet0_n]

set_property PACKAGE_PIN V14 [get_ports {leds[2]}]
set_property PACKAGE_PIN V13 [get_ports {leds[1]}]
set_property PACKAGE_PIN V12 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PULLUP true [get_ports {leds[2]}]
set_property PULLUP true [get_ports {leds[1]}]
set_property PULLUP true [get_ports {leds[0]}]
set_property DRIVE 8 [get_ports {leds[2]}]
set_property DRIVE 8 [get_ports {leds[1]}]
set_property DRIVE 8 [get_ports {leds[0]}]

# 0..3 are connector pins 1, 2, 4, 5
set_property PACKAGE_PIN A14 [get_ports iocon[0]]
set_property PACKAGE_PIN A13 [get_ports iocon[1]]
set_property PACKAGE_PIN B12 [get_ports iocon[2]]
set_property PACKAGE_PIN A12 [get_ports iocon[3]]
set_property IOSTANDARD LVCMOS33 [get_ports iocon[0]]
set_property IOSTANDARD LVCMOS33 [get_ports iocon[1]]
set_property IOSTANDARD LVCMOS33 [get_ports iocon[2]]
set_property IOSTANDARD LVCMOS33 [get_ports iocon[3]]

set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
