# Copyright (c) 2019-2024, NVIDIA CORPORATION.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

ifdef NV_BUILD_DGPU
	KBUILD_CFLAGS += \
		-I$(NVIDIA_SRC_DIR) \
		-DNV_BUILD_DGPU
	KBUILD_EXTRA_SYMBOLS=/usr/src/nvidia-535.171.04/Module.symvers
else
	ifdef NV_BUILD_IGX
		KBUILD_EXTRA_SYMBOLS=$(NVIDIA_EXTRA_SYMBOLS)
		ccflags-y += -I$(NVIDIA_SRC_DIR)
	else
		KBUILD_EXTRA_SYMBOLS=/usr/src/nvidia/nvidia-oot/Module.symvers
		ccflags-y += -I/usr/src/nvidia/nvidia-oot/include/
	endif
endif

ifdef NV_BUILD_NO_CUDA
	KBUILD_CFLAGS += \
		-DNV_BUILD_NO_CUDA
endif

obj-m += picoevb-rdma.o
