/*
 * Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 */

#ifndef __PICOEVB_RDMA_H__
#define __PICOEVB_RDMA_H__

#include <linux/types.h>

struct xlnx_dma_desc {
	u32 control;
	u32 len;
	u32 src_adr;
	u32 src_adr_hi;
	u32 dst_adr;
	u32 dst_adr_hi;
	u32 nxt_adr;
	u32 nxt_adr_hi;
} __packed;
#define XLNX_DMA_DESC_CONTROL_MAGIC		(0xad4bUL << 16)
#define XLNX_DMA_DESC_CONTROL_NEXT_ADJ_SHIFT	8
#define XLNX_DMA_DESC_CONTROL_NEXT_ADJ_MASK	0x3f
#define XLNX_DMA_DESC_CONTROL_EOP		BIT(4)
#define XLNX_DMA_DESC_CONTROL_COMPLETED		BIT(1)
#define XLNX_DMA_DESC_CONTROL_STOP		BIT(0)

#define XLNX_DMA_SUBSYS_ID			0x1fc

#define XLNX_DMA_TARGET_H2C			0
#define XLNX_DMA_TARGET_C2H			1
#define XLNX_DMA_TARGET_IRQ			2
#define XLNX_DMA_TARGET_CONFIG			3
#define XLNX_DMA_TARGET_H2C_SGDMA		4
#define XLNX_DMA_TARGET_C2H_SGDMA		5
#define XLNX_DMA_TARGET_SGDMA			6

#define XLNX_REG(_target_, _channel_, _reg_) \
	((XLNX_DMA_TARGET_##_target_ << 12) | \
	((_channel_) << 8) | \
	XLNX_DMA_##_reg_)

/* H2C and C2H blocks: registers are almost identical */

#define XLNX_DMA_H2C_ID				0x00
#define XLNX_DMA_H2C_ID_SUBSYS_ID_SHIFT		20
#define XLNX_DMA_H2C_ID_SUBSYS_ID_MASK		0xfffU
#define XLNX_DMA_H2C_ID_TGT_SHIFT		16
#define XLNX_DMA_H2C_ID_TGT_MASK		0xfU
#define XLNX_DMA_H2C_ID_AXI_STREAM		BIT(15)
#define XLNX_DMA_H2C_ID_CH_ID_SHIFT		8
#define XLNX_DMA_H2C_ID_CH_ID_MASK		0xfU
#define XLNX_DMA_H2C_ID_VER_SHIFT		0
#define XLNX_DMA_H2C_ID_VER_MASK		0xfU

#define XLNX_DMA_H2C_CTRL			0x04
#define XLNX_DMA_H2C_CTRL_STREAM_WB_DIS		BIT(27)
#define XLNX_DMA_H2C_CTRL_POLLMODE_WB_EN	BIT(26)
#define XLNX_DMA_H2C_CTRL_NON_INC_MOD		BIT(25)
#define XLNX_DMA_H2C_CTRL_IE_DESC_ERR_SHIFT	19
#define XLNX_DMA_H2C_CTRL_IE_DESC_ERR_MASK	0x1fU
/* WRITE_ERR H2C only; not C2H */
#define XLNX_DMA_H2C_CTRL_IE_WRITE_ERR_SHIFT	14
#define XLNX_DMA_H2C_CTRL_IE_WRITE_ERR_MASK	0x1fU
#define XLNX_DMA_H2C_CTRL_IE_READ_ERR_SHIFT	9
#define XLNX_DMA_H2C_CTRL_IE_READ_ERR_MASK	0x1fU
#define XLNX_DMA_H2C_CTRL_IE_IDLE_STOPPED	BIT(6)
#define XLNX_DMA_H2C_CTRL_IE_INVALID_LEN	BIT(5)
#define XLNX_DMA_H2C_CTRL_IE_MAGIC_STOPPED	BIT(4)
#define XLNX_DMA_H2C_CTRL_IE_ALIGN_MISMATCH	BIT(3)
#define XLNX_DMA_H2C_CTRL_IE_DESC_COMPLETED	BIT(2)
#define XLNX_DMA_H2C_CTRL_IE_DESC_STOPPED	BIT(1)
#define XLNX_DMA_H2C_CTRL_RUN			BIT(0)

#define XLNX_DMA_H2C_CTRL_W1S			0x08

#define XLNX_DMA_H2C_CTRL_W1C			0x0c

#define XLNX_DMA_H2C_STATUS			0x40
#define XLNX_DMA_H2C_STATUS_DESC_ERR_SHIFT	19
#define XLNX_DMA_H2C_STATUS_DESC_ERR_MASK	0x1fU
/* WRITE_ERR H2C only; not C2H */
#define XLNX_DMA_H2C_STATUS_WRITE_ERR_SHIFT	14
#define XLNX_DMA_H2C_STATUS_WRITE_ERR_MASK	0x1fU
#define XLNX_DMA_H2C_STATUS_READ_ERR_SHIFT	9
#define XLNX_DMA_H2C_STATUS_READ_ERR_MASK	0x1fU
#define XLNX_DMA_H2C_STATUS_IDLE_STOPPED	BIT(6)
#define XLNX_DMA_H2C_STATUS_INVALID_LEN		BIT(5)
#define XLNX_DMA_H2C_STATUS_MAGIC_STOPPED	BIT(4)
#define XLNX_DMA_H2C_STATUS_ALIGN_MISMATCH	BIT(3)
#define XLNX_DMA_H2C_STATUS_DESC_COMPLETED	BIT(2)
#define XLNX_DMA_H2C_STATUS_DESC_STOPPED	BIT(1)
#define XLNX_DMA_H2C_STATUS_BUSY		BIT(0)

#define XLNX_DMA_H2C_STATUS_RD_CLR		0x44

#define XLNX_DMA_H2C_COMPLETED_DESC_COUNT	0x48

#define XLNX_DMA_H2C_INT_EN			0x90
#define XLNX_DMA_H2C_IM_DESC_ERR_SHIFT		19
#define XLNX_DMA_H2C_IM_DESC_ERR_MASK		0x1fU
/* WRITE_ERR H2C only; not C2H */
#define XLNX_DMA_H2C_IM_WRITE_ERR_SHIFT		14
#define XLNX_DMA_H2C_IM_WRITE_ERR_MASK		0x1fU
#define XLNX_DMA_H2C_IM_READ_ERR_SHIFT		9
#define XLNX_DMA_H2C_IM_READ_ERR_MASK		0x1fU
#define XLNX_DMA_H2C_IM_IDLE_STOPPED		BIT(6)
#define XLNX_DMA_H2C_IM_INVALID_LEN		BIT(5)
#define XLNX_DMA_H2C_IM_MAGIC_STOPPED		BIT(4)
#define XLNX_DMA_H2C_IM_ALIGN_MISMATCH		BIT(3)
#define XLNX_DMA_H2C_IM_DESC_COMPLETED		BIT(2)
#define XLNX_DMA_H2C_IM_DESC_STOPPED		BIT(1)

#define XLNX_DMA_H2C_INT_EN_W1S			0x94

#define XLNX_DMA_H2C_INT_EN_W1C			0x98

/* IRQ block */

#define XLNX_DMA_IRQ_ID				0x00
#define XLNX_DMA_IRQ_ID_SUBSYS_ID_SHIFT		20
#define XLNX_DMA_IRQ_ID_SUBSYS_ID_MASK		0xfffU
#define XLNX_DMA_IRQ_ID_TGT_SHIFT		16
#define XLNX_DMA_IRQ_ID_TGT_MASK		0xfU
#define XLNX_DMA_IRQ_ID_VER_SHIFT		0
#define XLNX_DMA_IRQ_ID_VER_MASK		0xfU

#define XLNX_DMA_IRQ_CH_H2C_BIT(channel) \
	BIT(channel)
#define XLNX_DMA_IRQ_CH_C2H_BIT(channel, num_h2c)\
	BIT((channel) + (num_h2c))

#define XLNX_DMA_IRQ_CH_INT_EN			0x10

#define XLNX_DMA_IRQ_CH_INT_EN_W1S		0x14

#define XLNX_DMA_IRQ_CH_INT_EN_W1C		0x18

#define XLNX_DMA_IRQ_CH_PENDING			0x4c

/* Config block */

#define XLNX_DMA_CONFIG_ID			0x00
#define XLNX_DMA_CONFIG_ID_SUBSYS_ID_SHIFT	20
#define XLNX_DMA_CONFIG_ID_SUBSYS_ID_MASK	0xfffU
#define XLNX_DMA_CONFIG_ID_TGT_SHIFT		16
#define XLNX_DMA_CONFIG_ID_TGT_MASK		0xfU
#define XLNX_DMA_CONFIG_ID_VER_SHIFT		0
#define XLNX_DMA_CONFIG_ID_VER_MASK		0xfU

/* H2C and C2H SGDMA blocks: registers are almost identical */

#define XLNX_DMA_H2C_SGDMA_ID			0x00
#define XLNX_DMA_H2C_SGDMA_ID_SUBSYS_ID_SHIFT	20
#define XLNX_DMA_H2C_SGDMA_ID_SUBSYS_ID_MASK	0xfffU
#define XLNX_DMA_H2C_SGDMA_ID_TGT_SHIFT		16
#define XLNX_DMA_H2C_SGDMA_ID_TGT_MASK		0xfU
#define XLNX_DMA_H2C_SGDMA_ID_AXI_STREAM	BIT(15)
#define XLNX_DMA_H2C_SGDMA_ID_CH_ID_SHIFT	8
#define XLNX_DMA_H2C_SGDMA_ID_CH_ID_MASK	0xfU
#define XLNX_DMA_H2C_SGDMA_ID_VER_SHIFT		0
#define XLNX_DMA_H2C_SGDMA_ID_VER_MASK		0xfU

#define XLNX_DMA_H2C_SGDMA_DESC_LOW_ADDR	0x80

#define XLNX_DMA_H2C_SGDMA_DESC_HIGH_ADDR	0x84

#define XLNX_DMA_H2C_SGDMA_DESC_ADJACENT	0x88

/* SGDMA common block */

#define XLNX_DMA_SGDMA_CMN_ID			0x00
#define XLNX_DMA_SGDMA_CMN_ID_SUBSYS_ID_SHIFT	20
#define XLNX_DMA_SGDMA_CMN_ID_SUBSYS_ID_MASK	0xfffU
#define XLNX_DMA_SGDMA_CMN_ID_TGT_SHIFT		16
#define XLNX_DMA_SGDMA_CMN_ID_TGT_MASK		0xfU
#define XLNX_DMA_SGDMA_CMN_ID_VER_SHIFT		0
#define XLNX_DMA_SGDMA_CMN_ID_VER_MASK		0xfU

#define XLNX_DMA_SGDMA_CTRL			0x10
#define XLNX_DMA_SGDMA_CTRL_C2H_DSC_HALT_SHIFT	16
#define XLNX_DMA_SGDMA_CTRL_C2H_DSC_HALT_MASK	0xfU
#define XLNX_DMA_SGDMA_CTRL_H2C_DSC_HALT_SHIFT	0
#define XLNX_DMA_SGDMA_CTRL_H2C_DSC_HALT_MASK	0xfU

#define XLNX_DMA_SGDMA_CTRL_W1S			0x14

#define XLNX_DMA_SGDMA_CTRL_W1C			0x18

#endif
